services:
  - type: static
    name: nuricar-manage
    buildCommand: npm install && npm run build
    staticPublishPath: dist/Nuricar-Management
    routes:
      - type: redirect
        source: /cars
        destination: /
        statusCode: 301
      - type: redirect
        source: /icons
        destination: /
        statusCode: 301
      - type: redirect
        source: /missing
        destination: /
        statusCode: 301     
      - type: rewrite
        source: /*
        destination: /index.html
